### ISSUE TITLE
Score Update 

### ISSUE THREAD

**Issue by cpsc-helper** [DeepPSP/cpsc2021#1]
The latest score: 1.9766

**Comment by cpsc-helper** [comment]
The latest score: 1.7829

**Comment by wenh06** [comment]
> The latest score: 1.9766

lstm + seq_lab, union

**Comment by wenh06** [comment]
> The latest score: 1.7829

lstm + unet, union

**Comment by cpsc-helper** [comment]
The latest score: 1.9392

**Comment by wenh06** [comment]
> The latest score: 1.9392

lstm

**Comment by cpsc-helper** [comment]
The latest score: 1.3699

**Comment by wenh06** [comment]
> The latest score: 1.3699

unet

**Comment by cpsc-helper** [comment]
The latest score: 1.9781

**Comment by wenh06** [comment]
> The latest score: 1.9781

seq_lab

**Comment by cpsc-helper** [comment]
The latest score: 1.9287

**Comment by wenh06** [comment]
> The latest score: 1.9287

lstm + seq_lab, intersection

**Comment by cpsc-helper** [comment]
The latest score: 1.9766

**Comment by cpsc-helper** [comment]
The latest score: 1.9781
